### ISSUE TITLE
Code is not user friendly

### ISSUE THREAD

**Issue by syddo** [rolanmolano/cs204#1]
Your code is not very user friendly.
The commit comment is also not very useful.

Syd was here.

**Comment by rolanmolano** [comment]
POTA KA! ahahahahahahh






-- 
Regards.

*Rol**a**n Eleazer T. Molano, MSCS*
*Chief Science Research Specialist at DOST PCAARRD *
*Management Information System Division *
Email: rtmo <rtmolano@up.edu.ph>la <rtmolano@up.edu.ph>no@up.edu.ph
<rtmolano@up.edu.ph> || rtmolano@uplb.edu.ph || rtmolano@rolanmolano.com
<rtmolano@rolanmolano.com> || rolanmolano_77 <rolanmolano_77@yahoo.com>@
<rolanmolano_77@yahoo.com>yahoo.com <rolanmolano_77@yahoo.com>
Website: www.rolanmolano.com || Linkedin:
https://ph.linkedin.com/in/rolan-eleazer-molano-0364a993
Mobile: 09175770805



*Department of Science and Technology*
*Philippine Council for Agriculture, Aquatic and Natural Resources Research
and Development (PCAARRD)*

*http://www.pcaarrd.dost.gov.ph <http://www.pcaarrd.dost.gov.ph/>*
